api_platform:
    title: 'Symfony REST API'
    description: 'APi Symfony de gestion des taches'
    version: '1.0.0'
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
    defaults:
        pagination_items_per_page: 30 # Default value    
